const interests=["Artificial Intelligence","Startups","World Affairs","Markets","History","Science","Product","China ↔ US"];
const sources=["Hacker News","New York Times","Financial Times","TechCrunch","The Verge","OpenAI","Company blogs"];
const stories=[
 {id:1,source:"Hacker News",topic:"AI",title:"Smaller models are moving from demos into everyday tools",dek:"A practical shift toward faster, private, task-specific intelligence.",why:"Matches AI · useful for product builders",mins:3},
 {id:2,source:"Financial Times",topic:"Markets",title:"The infrastructure race behind the next wave of compute",dek:"Capital, energy, and chips are becoming one interconnected story.",why:"Connects markets with your AI interest",mins:3},
 {id:3,source:"OpenAI",topic:"Research",title:"A new approach to making agents more dependable",dek:"What better tool use could mean—and what remains stubbornly hard.",why:"New since your last briefing",mins:2},
 {id:4,source:"New York Times",topic:"World",title:"Technology policy becomes a trans-Pacific balancing act",dek:"The decisions shaping how US and Chinese ecosystems evolve.",why:"Matches China ↔ US",mins:3},
 {id:5,source:"TechCrunch",topic:"Startups",title:"Founders rethink the application layer for AI",dek:"New products compete on context, workflow, and distribution.",why:"Relevant to early-stage builders",mins:2},
 {id:6,source:"The Verge",topic:"Product",title:"Voice interfaces quietly find their second act",dek:"Less assistant, more companion: audio products are narrowing their jobs.",why:"Highly relevant to this product",mins:2}
];
const state={selected:new Set([1,3]),playing:false,progress:0,timer:null};
const $=s=>document.querySelector(s);

function chip(label,selected=false){const b=document.createElement("button");b.className=`chip${selected?" selected":""}`;b.textContent=label;b.onclick=()=>b.classList.toggle("selected");return b}
function renderChips(){interests.forEach((x,i)=>$("#interestChips").append(chip(x,[0,1,6,7].includes(i))));sources.forEach((x,i)=>$("#sourceChips").append(chip(x,[0,2,5].includes(i))))}
function renderFeed(){const grid=$("#feedGrid");grid.innerHTML="";stories.forEach(s=>{const el=document.createElement("article");el.className=`story-card${state.selected.has(s.id)?" selected":""}`;el.tabIndex=0;el.innerHTML=`<div class="story-meta"><span>${s.source}</span><i></i><span>${s.topic}</span></div><h3>${s.title}</h3><p>${s.dek}</p><p class="why">✦ ${s.why}</p>`;const toggle=()=>{state.selected.has(s.id)?state.selected.delete(s.id):state.selected.add(s.id);renderFeed();renderQueue()};el.onclick=toggle;el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();toggle()}};grid.append(el)})}
function renderQueue(){const selected=stories.filter(s=>state.selected.has(s.id));$("#queueCount").textContent=selected.length;$("#estimate").textContent=`~${selected.reduce((n,s)=>n+s.mins,0)+2} min`;$("#generateBtn").disabled=!selected.length;$("#queueItems").innerHTML=selected.length?selected.map(s=>`<span class="queue-pill">${s.source} · ${s.title.split(" ").slice(0,6).join(" ")}…</span>`).join(""):'<p class="empty">Choose a few stories above. We’ll find the thread between them.</p>'}
function updateProfile(){const region=$("#region").value.replace("San Francisco ","");const level=$("#level").value;const duration=$("#duration").value;$("#profileStrip").querySelectorAll("span")[0].textContent=region;$("#profileStrip").querySelectorAll("span")[1].textContent=level;$("#profileStrip").querySelectorAll("span")[2].textContent=`${duration} briefing`}
function generate(){$("#queuePanel").classList.add("hidden");$("#generationPanel").classList.remove("hidden");$("#generationPanel").scrollIntoView({behavior:"smooth",block:"center"});let step=0;const titles=["Reading across your sources…","Removing repetition and finding the thread…","Writing for your knowledge level…","Giving your briefing a voice…"];const widths=[18,43,72,100];const timer=setInterval(()=>{step++;if(step===4){clearInterval(timer);setTimeout(showPlayer,500);return}$("#generationTitle").textContent=titles[step];$("#progressBar").style.width=`${widths[step]}%`;document.querySelectorAll(".generation-steps span").forEach((x,i)=>x.classList.toggle("active",i<=step))},850)}
function showPlayer(){$("#generationPanel").classList.add("hidden");const selected=stories.filter(s=>state.selected.has(s.id));$("#episodeSummary").textContent=`A personal ${selected.reduce((n,s)=>n+s.mins,0)+2}-minute briefing connecting ${selected.slice(0,2).map(s=>s.topic.toLowerCase()).join(" and ")}—with context, implications, and the questions worth carrying into your day.`;$("#chapters").innerHTML=selected.map((s,i)=>`<span class="chapter">${i*3}:0${i} · ${s.topic}</span>`).join("");$("#playerPanel").classList.remove("hidden");$("#playerPanel").scrollIntoView({behavior:"smooth",block:"center"})}
function togglePlay(){state.playing=!state.playing;$("#playBtn").textContent=state.playing?"Ⅱ":"▶";if(state.playing){state.timer=setInterval(()=>{state.progress=Math.min(100,state.progress+.25);$("#seek").value=state.progress;const sec=Math.floor(738*state.progress/100);$("#currentTime").textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,"0")}`;if(state.progress>=100)togglePlay()},500)}else clearInterval(state.timer)}

document.addEventListener("DOMContentLoaded",()=>{$("#dateLabel").textContent=new Intl.DateTimeFormat("en-US",{weekday:"short",month:"short",day:"numeric"}).format(new Date());renderChips();renderFeed();renderQueue();$("#editProfile").onclick=()=>{$("#onboardingPanel").classList.toggle("hidden");$("#onboardingPanel").scrollIntoView({behavior:"smooth",block:"center"})};$("#closeProfile").onclick=()=>{$("#onboardingPanel").classList.add("hidden");updateProfile()};$("#generateBtn").onclick=generate;$("#playBtn").onclick=togglePlay;$("#seek").oninput=e=>{state.progress=+e.target.value};$("#refreshFeed").onclick=()=>{stories.push(stories.shift());renderFeed()};$("#feedbackBtn").onclick=e=>{e.target.textContent="✓ Feedback saved";e.target.disabled=true}});
