const state={items:[],selected:new Set(),episode:null,speaking:false};
const $=id=>document.getElementById(id);
const escapeHTML=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]);
const sourceName=s=>s==="Hugging Face Daily Papers"?"Daily Papers":s;
function sources(){return [...document.querySelectorAll('.source-option input:checked')].map(x=>x.value)}
function updateSelection(){const chosen=state.items.filter(x=>state.selected.has(x.id));$('selectedCount').textContent=`${chosen.length} / 5 selected`;$('selectionPreview').innerHTML=chosen.length?chosen.map(x=>`<div>✓ ${escapeHTML(x.title)}</div>`).join(''):'Your selected stories will appear here.';$('generateBtn').disabled=!chosen.length}
function renderItems(){const list=$('storyList');$('resultCount').textContent=`${state.items.length} fresh items`;if(!state.items.length){list.innerHTML='<div class="placeholder">No items found. Try another source or refresh.</div>';updateSelection();return}list.innerHTML=state.items.map(x=>{const hasAbstract=!!x.summary;return `<label class="story"><input type="checkbox" data-id="${escapeHTML(x.id)}" ${state.selected.has(x.id)?'checked':''}><span><span class="story-meta">${escapeHTML(sourceName(x.source))} · ${escapeHTML((x.published_at||'').slice(0,10)||'Date unknown')}</span><h3>${escapeHTML(x.title)}</h3><p>${escapeHTML((x.summary||'Article text not fetched. This is a headline-only candidate.').slice(0,250))}${x.summary?.length>250?'…':''}</p><span class="evidence ${hasAbstract?'':'headline'}">${hasAbstract?'Abstract available':'Headline only'}</span> <a href="${escapeHTML(x.url)}" target="_blank" rel="noopener noreferrer" onclick="event.stopPropagation()">Original ↗</a></span></label>`}).join('');list.querySelectorAll('input[data-id]').forEach(input=>input.addEventListener('change',()=>{if(input.checked&&state.selected.size>=5){input.checked=false;$('feedStatus').textContent='Choose up to five items.';return}input.checked?state.selected.add(input.dataset.id):state.selected.delete(input.dataset.id);updateSelection()}));updateSelection()}
async function fetchItems(){const chosen=sources();if(!chosen.length){$('feedStatus').textContent='Select at least one source.';return}$('refreshBtn').disabled=true;$('feedStatus').textContent='Fetching fresh candidates…';try{const params=new URLSearchParams();chosen.forEach(s=>params.append('source',s));const response=await fetch(`/api/candidates?${params}`);const data=await response.json();state.items=data.items||[];state.selected.clear();renderItems();$('feedStatus').textContent=data.warnings?.length?`${state.items.length} items loaded · ${data.warnings.join('; ')}`:`${state.items.length} items loaded. Choose what interests you.`}catch(error){$('feedStatus').textContent='Could not fetch items. Check your connection and retry.'}finally{$('refreshBtn').disabled=false}}
function renderReport(episode){state.episode=episode;$('reportTitle').textContent=episode.title;$('reportMeta').textContent=`${episode.chapters.length} sources · ${episode.model} · ${new Date(episode.created_at).toLocaleString()}`;const paragraphs=episode.script.split(/\n\s*\n/);$('reportIntro').textContent=paragraphs[0]||'';$('reportClosing').textContent=paragraphs.at(-1)||'';$('reportChapters').innerHTML=episode.chapters.map((ch,i)=>`<article class="report-chapter"><span class="story-meta">${escapeHTML(ch.source)} · ${escapeHTML(ch.evidence_level.replaceAll('_',' '))}</span><h3>${i+1}. ${escapeHTML(ch.title)}</h3><p>${escapeHTML(ch.narration)}</p><a href="${escapeHTML(ch.url)}" target="_blank" rel="noopener noreferrer">Read original ↗</a></article>`).join('');$('reportPanel').classList.remove('hidden');$('reportPanel').scrollIntoView({behavior:'smooth',block:'start'})}
async function generate(){const ids=[...state.selected];if(!ids.length)return;$('generateBtn').disabled=true;$('generateBtn').innerHTML='Writing your report… <span>◌</span>';try{const response=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids,model:$('modelSelect').value,focus:$('focusInput').value})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Generation failed');renderReport(data.episode);$('feedStatus').textContent='Report ready. Review its source links before sharing.'}catch(error){$('feedStatus').textContent=error.message}finally{$('generateBtn').innerHTML='Generate report <span>→</span>';updateSelection()}}
function listen(){if(!('speechSynthesis' in window)){$('listenBtn').textContent='Browser speech unavailable';return}if(state.speaking){speechSynthesis.cancel();state.speaking=false;$('listenBtn').textContent='Listen in browser ▶';return}if(!state.episode)return;const utterance=new SpeechSynthesisUtterance(state.episode.script);utterance.rate=.95;utterance.onend=utterance.onerror=()=>{state.speaking=false;$('listenBtn').textContent='Listen in browser ▶'};speechSynthesis.speak(utterance);state.speaking=true;$('listenBtn').textContent='Stop listening ■'}
document.addEventListener('DOMContentLoaded',()=>{$('refreshBtn').onclick=fetchItems;$('generateBtn').onclick=generate;$('listenBtn').onclick=listen;fetchItems()});
